### ISSUE TITLE
Test for dead fixtures in pytest

### ISSUE THREAD

**Issue by etcher-be** [etcher-be/epab#10]
https://github.com/jllorencetti/pytest-deadfixtures/blob/master/README.rst

**Comment by 132nd-etcher** [comment]
pytest-deadfixtures seems to break coverage

**Comment by 132nd-etcher** [comment]
pytest-deadfixtures seems to break coverage

**Comment by jllorencetti** [comment]
Hi @132nd-etcher.

I took a quick look at the build log and the problem is that the `--dead-fixtures` command is being used together with the pytest suit run itself.
This command cause the tests not to run, that's probably the reason why the coverage is being broken.
What you can do is add the plugin run as a separate build step, and keep running the tests as you did before, like [this](https://github.com/jllorencetti/pytest-deadfixtures/blob/master/.travis.yml#L21).

I'll update the plugin README to better explain this.

Thanks for trying it out. :)

**Comment by 132nd-etcher** [comment]
@jllorencetti Hey man, thanks a bunch for popping up, much appreciated ! I understand the issue and why it happens, it makes a lot of sense actually. I'll add this to my work flow soon as I have spare programming time !

Thanks again for your help !

**Comment by etcher-be** [comment]
@jllorencetti it's working perfectly on my end now, thanks again for the help !
